### ISSUE TITLE
[Feature Request] One-button to lock all achievements

### ISSUE THREAD

**Issue by SekiBetu** [unencouraged/SAM-Auto#1]
https://github.com/gibbed/SteamAchievementManager/issues/35#issuecomment-904421604

**Comment by bigfinfrank** [comment]
Any chance this will ever get added @unencouraged?

**Comment by unencouraged** [comment]
> Any chance this will ever get added @unencouraged?

Done, you can get the updated build here: https://github.com/unencouraged/SAM-Auto/releases/tag/v1.1
